'use client';
import { useEffect, useRef, useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowUpRight, Check, RotateCcw, ShieldCheck, Sparkles, ArrowUp, Menu } from 'lucide-react';
import { Hero } from './hero';
import { SourceIcon } from './source-icon';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
import { useDemoStore } from '@/lib/store';
import { getDemoAnswer, sources, questions } from '@/lib/demo';
import { useAuth } from './auth/auth-provider';

function Brand() { return <a className="brand" href="#overview" aria-label="Layer home"><img src="/layer-logo.svg" alt="" width="38" height="38"/><span>Layer</span></a> }
function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={{opacity:reduced?1:0,y:reduced?0:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65}}>{children}</motion.div>}
function Demo(){
 const {question,setQuestion}=useDemoStore();
 const [citation,setCitation]=useState<number|null>(null);
 const [replay,setReplay]=useState(0);
 const {data,isPending}=useQuery({queryKey:['demo-answer',question],queryFn:()=>getDemoAnswer(question)});
 const source=sources.find(item=>item.id===citation);
 return <section className="demo section-wrap" id="demo"><Reveal><div className="section-heading"><p className="eyebrow-label">LAYER IN ACTION</p><h2>One question. The whole context.</h2><p>Pick a question. Watch the pieces come together.</p></div>
 <Tabs value={question} onValueChange={setQuestion}><TabsList className="question-tabs">{Object.entries(questions).map(([key,item])=><TabsTrigger value={key} key={key}>{item.label}</TabsTrigger>)}</TabsList></Tabs>
 <div className="demo-canvas"><div className="source-list">{sources.map(item=><button key={item.id} onClick={()=>setCitation(item.id)} className={`source-row ${data&&!data.lines.some(line=>line.source===item.id)?'source-muted':''}`}><SourceIcon type={item.type}/><span><strong>{item.title}</strong><small>{item.name} · {item.detail}</small></span><ArrowUpRight size={17}/></button>)}</div><div className="demo-bridge" aria-hidden="true"><div/><img src="/layer-logo.svg" alt=""/><div/></div><article className="answer-panel" aria-live="polite" aria-busy={isPending}><div className="answer-panel-heading"><span><img src="/layer-logo.svg" alt=""/> Layer</span><small>PROJECT BRIEF</small></div>{isPending?<div className="answer-loading">Finding the pieces…</div>:<motion.div key={`${question}-${replay}`} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><h3>{data?.title}</h3>{data?.lines.map((line,i)=><p key={i}>{line.text} <button className="citation-number" onClick={()=>setCitation(line.source)} aria-label={`View source ${line.source}`}>{line.source}</button></p>)}</motion.div>}<div className="answer-footer"><span><ShieldCheck size={15}/> {data?`${data.lines.length} of ${data.lines.length} claims verified`:'Checking evidence'}</span><button onClick={()=>setReplay(value=>value+1)}><RotateCcw size={14}/> Replay</button></div></article></div><p className="demo-caption">Interactive example · Phoenix Launch · Sample data</p></Reveal>
 <Dialog open={citation!==null} onOpenChange={open=>{if(!open)setCitation(null)}}><DialogContent className="source-dialog"><p className="eyebrow-label">{source?.name} · SOURCE {source?.id}</p><DialogTitle>{source?.title}</DialogTitle><DialogDescription>Evidence from the Phoenix Launch example.</DialogDescription><blockquote>“{source?.text}”</blockquote><span className="verified"><Check size={16}/> Cited in the answer</span></DialogContent></Dialog></section>
}
const connectors=[{key:'drive',name:'Google Drive',tagline:'Give your docs a voice',mode:'SELECT & SYNC',description:'Choose the Drive files that belong to your project. Layer brings them into your project’s knowledge and refreshes them when you sync.'},{key:'gmail',name:'Gmail',tagline:'Keep up with the conversation',mode:'SEARCH LIVE',description:'Focus on the emails that matter with labels, senders, and keywords. Layer searches them when you ask, so recent decisions can inform the answer.'},{key:'jira',name:'Jira',tagline:'Know what’s moving. Or isn’t.',mode:'SEARCH LIVE',description:'Connect your Jira project. Layer searches its tickets when you ask, bringing open blockers and changing statuses into the conversation.'},{key:'notion',name:'Notion',tagline:'Turn team notes into context',mode:'SEARCH LIVE',description:'Choose your project’s Notion pages and databases. Layer searches within those sources for plans, tasks, and the context behind your work.'}];
function Connections(){return <section className="connections section-wrap" id="connections"><Reveal><div className="section-heading"><h2>Your work lives everywhere.<br/>Its context lives here.</h2><p>Keep the tools you use. Connect the knowledge inside them.</p></div><Tabs defaultValue="drive"><TabsList className="connector-tabs">{connectors.map(item=><TabsTrigger value={item.key} key={item.key}><SourceIcon type={item.key}/><strong>{item.name}</strong><span>{item.tagline}</span></TabsTrigger>)}</TabsList>{connectors.map(item=><TabsContent value={item.key} key={item.key} className="connector-content"><span>{item.mode}</span><p>{item.description}</p></TabsContent>)}</Tabs></Reveal></section>}
const memorySchema=z.object({fact:z.string().trim().min(1,'Add a fact before approving.').max(160,'Keep the fact under 160 characters.')});
function Memory(){
 const [editing,setEditing]=useState(false);const [decision,setDecision]=useState<'approved'|'skipped'|null>(null);
 const form=useForm<z.infer<typeof memorySchema>>({resolver:zodResolver(memorySchema),defaultValues:{fact:'Phoenix launch date is November 15.'}});
 return <section className="memory-section wide-section" id="memory"><Reveal className="split-section"><div><p className="eyebrow-label">A MEMORY. WITH YOUR PERMISSION.</p><h2>Picks up where<br/>you left off.</h2><p>Important decisions shouldn’t disappear in a chat. Layer can remember them for next time.</p><strong className="memory-emphasis">You decide what stays.</strong></div><div className="memory-demo"><form className="memory-card" onSubmit={form.handleSubmit(()=>{setDecision('approved');setEditing(false)})}><div className="memory-top"><Sparkles size={23}/><span>PROJECT MEMORY</span><small>Try it</small></div><h3>Worth remembering?</h3><p>Layer noticed an update to Phoenix Launch.</p><label htmlFor="memory-fact" className="sr-only">Proposed project memory</label><Input id="memory-fact" {...form.register('fact')} readOnly={!editing} className="memory-input" aria-invalid={!!form.formState.errors.fact} aria-describedby={form.formState.errors.fact?'memory-error':undefined}/>{form.formState.errors.fact&&<p id="memory-error" className="form-error">{form.formState.errors.fact.message}</p>}{decision?<div className="memory-result" role="status">{decision==='approved'?<><Check size={18}/> Approved. Ready for your next conversation.</>:'Skipped. This fact won’t be remembered.'}</div>:<div className="memory-buttons"><Button type="submit" className="pill"><Check/> Approve</Button><Button type="button" variant="outline" className="pill" onClick={()=>{setEditing(true);setTimeout(()=>form.setFocus('fact'),0)}}>Edit</Button><button type="button" onClick={()=>setDecision('skipped')}>Skip</button></div>}</form><div className="memory-note"><span>{decision?'Demo only — no project data is saved.':'Nothing is remembered without your approval.'}</span>{decision&&<button onClick={()=>{setDecision(null);setEditing(false);form.reset()}}>Try again <RotateCcw size={13}/></button>}</div></div></Reveal></section>
}
function Evidence(){const [expanded,setExpanded]=useState(true);return <section className="trust-section wide-section"><Reveal className="split-section"><div><p className="eyebrow-label">ANSWERS WITH A PAPER TRAIL</p><h2>Don’t just take<br/>its word for it.</h2><p>Follow every claim back to its source. Layer checks whether the evidence supports its answer, and tells you when the context is missing.</p><a href="#demo" className="inline-link">Try the citations <ArrowUpRight size={18}/></a></div><div className="evidence-example"><div className="evidence-answer"><span className="eyebrow-label">THE ANSWER</span><p>The launch has moved to <strong>November 15.</strong> <button className="citation-number" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded} aria-controls="evidence-detail">4</button></p></div>{expanded&&<motion.div id="evidence-detail" className="evidence-detail" initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}}><div><SourceIcon type="gmail"/><span>Re: Phoenix launch date<small>Gmail · September 19</small></span></div><p>“We’re moving launch to <mark>Nov 15</mark> to give QA another week.”</p><span className="verified"><ShieldCheck size={16}/> Supported by this source</span></motion.div>}<small className="example-note">Example answer and source · Click [4] to explore.</small></div></Reveal></section>}
function FinalFooter(){
 const ref=useRef<HTMLElement>(null);
 const reduced=useReducedMotion();
 const [hiddenPercent,setHiddenPercent]=useState(100);
 useEffect(()=>{
  let frame=0;
  const update=()=>{
   const box=ref.current?.getBoundingClientRect();
   if(!box)return;
   const progress=Math.min(1,Math.max(0,(window.innerHeight-box.top)/box.height));
   setHiddenPercent(Math.max(0,Math.min(100,(1-progress)/.82*100)));
  };
  const schedule=()=>{if(!frame)frame=requestAnimationFrame(()=>{frame=0;update()})};
  update();const restoreTimer=window.setTimeout(update,250);
  window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);window.addEventListener('pageshow',schedule);
  return()=>{window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);window.removeEventListener('pageshow',schedule);window.clearTimeout(restoreTimer);cancelAnimationFrame(frame)};
 },[]);
 return <footer className="final-footer" ref={ref}><div className="footer-details"><Brand/><span>Your project, connected.</span><a href="#overview">Back to top <ArrowUp size={15}/></a></div><motion.div className="footer-wordmark" aria-hidden="true" style={reduced?undefined:{clipPath:`inset(0 0 ${hiddenPercent}% 0)`}} animate={{y:reduced?0:hiddenPercent*.85}} transition={reduced?{duration:0}:{type:'spring',stiffness:110,damping:24,mass:.8}}><span>Layer</span></motion.div></footer>;
}
export function Home(){const [menu,setMenu]=useState(false);const {user}=useAuth();return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><Brand/><nav aria-label="Main navigation" className={menu?'nav-open':''}><a href="#overview" className="nav-active" onClick={()=>setMenu(false)}>Overview</a><a href="#connections" onClick={()=>setMenu(false)}>Connections</a><a href="#memory" onClick={()=>setMenu(false)}>Memory</a><a href="#demo" onClick={()=>setMenu(false)}>Try Layer <ArrowUpRight size={18}/></a><a href={user?'/workspace':'/login'} onClick={()=>setMenu(false)}>{user?'Open workspace':'Log in'}</a></nav><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}><Menu/></button></header><main id="main"><Hero/><section className="how-section section-wrap" id="how-it-works"><Reveal className="how-layout"><div><h2>How it works</h2><p>You bring the project.<br/>Layer connects the dots.</p></div><div className="steps">{[{title:'Make space for your project.',text:'Give it a name. Keep its knowledge, conversations, and memories together.'},{title:'Bring the right sources.',text:'Choose the documents, emails, tickets, and pages that matter to this project.'},{title:'Ask the bigger questions.',text:'Layer finds the relevant evidence across your sources and brings it into one cited answer.'}].map((step,i)=><article key={step.title}><span>0{i+1}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></Reveal></section><Demo/><Connections/><Evidence/><Memory/><section className="closing section-wrap"><Reveal><img src="/layer-logo.svg" alt="" width="52" height="52"/><h2>Get to the<br/><span>“now I get it.”</span></h2><p>Your project has the answers. Bring them together.</p><Button className="pill" asChild><a href={user?'/workspace':'/register'}>{user?'Open workspace':'Get started'} <ArrowUpRight/></a></Button></Reveal></section></main><FinalFooter/></>}
